package com.zw.employee.mapper;

import com.zw.domain.Employee;
import com.zw.domain.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetable
     *
     * @mbggenerated Thu Nov 03 20:38:27 CST 2022
     */
    int countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetable
     *
     * @mbggenerated Thu Nov 03 20:38:27 CST 2022
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetable
     *
     * @mbggenerated Thu Nov 03 20:38:27 CST 2022
     */
    int deleteByPrimaryKey(String eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetable
     *
     * @mbggenerated Thu Nov 03 20:38:27 CST 2022
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetable
     *
     * @mbggenerated Thu Nov 03 20:38:27 CST 2022
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetable
     *
     * @mbggenerated Thu Nov 03 20:38:27 CST 2022
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetable
     *
     * @mbggenerated Thu Nov 03 20:38:27 CST 2022
     */
    Employee selectByPrimaryKey(String eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetable
     *
     * @mbggenerated Thu Nov 03 20:38:27 CST 2022
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetable
     *
     * @mbggenerated Thu Nov 03 20:38:27 CST 2022
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetable
     *
     * @mbggenerated Thu Nov 03 20:38:27 CST 2022
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetable
     *
     * @mbggenerated Thu Nov 03 20:38:27 CST 2022
     */
    int updateByPrimaryKey(Employee record);

    /**
     * 注册员工
     * @param employee
     * @return
     */
    int registeredEmployee(Employee employee);
//    查询所有员工
    List<Employee> queryEmployee();

    /**
     * 根据id删除员工
     */
    int deleteEmployeeById(String eid);

    /**
     * 根据id查询员工
     */
    Employee selectEmployeeById(String eid);

    /**
     * 修改员工信息
     * @param employee
     * @return
     */
    int updateEmployee(Employee employee);

    /**
     * 查询多个员工信息
     * @param eids
     * @return
     */
    List<Employee> selectEmployeeList(String[] eids);
}