package com.zw.wagescale.mapper;

import com.zw.domain.Jobscale;
import com.zw.domain.JobscaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobscaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:54 CST 2022
     */
    int countByExample(JobscaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:54 CST 2022
     */
    int deleteByExample(JobscaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:54 CST 2022
     */
    int deleteByPrimaryKey(Integer jid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:54 CST 2022
     */
    int insert(Jobscale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:54 CST 2022
     */
    int insertSelective(Jobscale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:54 CST 2022
     */
    List<Jobscale> selectByExample(JobscaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:54 CST 2022
     */
    Jobscale selectByPrimaryKey(Integer jid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:54 CST 2022
     */
    int updateByExampleSelective(@Param("record") Jobscale record, @Param("example") JobscaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:54 CST 2022
     */
    int updateByExample(@Param("record") Jobscale record, @Param("example") JobscaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:54 CST 2022
     */
    int updateByPrimaryKeySelective(Jobscale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:54 CST 2022
     */
    int updateByPrimaryKey(Jobscale record);
    /**
     * 录入各岗位工资一级标准
     */
    int insertJobscale(Jobscale jobscale);

    /**
     * 查询最新的岗位工资标准
     */
    Jobscale queryJobscale();

    /**
     * 根据id删除岗位工资标准
     * @param jid
     * @return
     */
    int deleteJobscale(String jid);

//    根据id查询岗位工资标准
    Jobscale getJobscaleByWid(String jid);

//    修改岗位工资标准
    int updateJobscale(Jobscale jobscale);
}