package com.zw.wagescale.mapper;

import com.zw.domain.Wagesscale;
import com.zw.domain.WagesscaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WagesscaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wagesscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    int countByExample(WagesscaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wagesscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    int deleteByExample(WagesscaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wagesscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    int deleteByPrimaryKey(String wid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wagesscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    int insert(Wagesscale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wagesscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    int insertSelective(Wagesscale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wagesscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    List<Wagesscale> selectByExample(WagesscaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wagesscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    Wagesscale selectByPrimaryKey(String wid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wagesscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    int updateByExampleSelective(@Param("record") Wagesscale record, @Param("example") WagesscaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wagesscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    int updateByExample(@Param("record") Wagesscale record, @Param("example") WagesscaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wagesscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    int updateByPrimaryKeySelective(Wagesscale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wagesscaletable
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    int updateByPrimaryKey(Wagesscale record);
    /**
     * 添加一条新的工资标准
     * @param wagesscale
     * @return
     */
    int createWagesscale(Wagesscale wagesscale);
    /**
     * 返回一条离当前时间最近的工资标准
     */
    Wagesscale queryMinTime();

    /**
     * 根据id查询工资标准
     * @param wid
     * @return
     */
    Wagesscale getWagesscaleByWid(String wid);

    /**
     * 修改工资标准信息
     * @param wagesscale
     * @return
     */
    int modifyWagesscale(Wagesscale wagesscale);

    /**
     * 删除指定工资标准
     */
    int deleteWagesscale(String wid);
}