package com.zw.calculation.mapper;

import com.zw.domain.Payslip;
import com.zw.domain.PayslipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayslipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paysliptable
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    int countByExample(PayslipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paysliptable
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    int deleteByExample(PayslipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paysliptable
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paysliptable
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    int insert(Payslip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paysliptable
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    int insertSelective(Payslip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paysliptable
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    List<Payslip> selectByExample(PayslipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paysliptable
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    Payslip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paysliptable
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    int updateByExampleSelective(@Param("record") Payslip record, @Param("example") PayslipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paysliptable
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    int updateByExample(@Param("record") Payslip record, @Param("example") PayslipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paysliptable
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    int updateByPrimaryKeySelective(Payslip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paysliptable
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    int updateByPrimaryKey(Payslip record);

    /**
     * 录入工资发放表
     */
    int insertPayslip(Payslip[] payslip);

    /**
     *根据员工号查询工资单记录
     */
    Payslip[] queryPayslips(String[] ids);

    /**
     * 根据员工号删除工资单记录
     */
    int deletePayslipsByEid(String[] ids);
}