package com.zw.performance.mapper;

import com.zw.domain.Performance;
import com.zw.domain.PerformanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bouncycastle.LICENSE;

public interface PerformanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performancetable
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    int countByExample(PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performancetable
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    int deleteByExample(PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performancetable
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performancetable
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    int insert(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performancetable
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    int insertSelective(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performancetable
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    List<Performance> selectByExample(PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performancetable
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    Performance selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performancetable
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") Performance record, @Param("example") PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performancetable
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    int updateByExample(@Param("record") Performance record, @Param("example") PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performancetable
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    int updateByPrimaryKeySelective(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performancetable
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    int updateByPrimaryKey(Performance record);

    /**
     * 插入具体表现情况
     * @param performance
     * @return
     */
    int insertPerformance(Performance performance);

    /**
     * 根据id查询员工具体表现情况
     */
    Performance selectPerformanceById(String eid);

    /**
     * 根据员工号删除员工所有具体表现情况
     */
    int deletePerformanceByEid(String eid);

    /**
     * 根据记录id删除员工具体表现情况中的一条记录
     */
    int deletePerformanceByPid(String pid);

    /**
     * 根据pid修改员工具体表现情况
     */
    int updatePerformanceByPid(Performance performance);

//    根据pid查询具体表现情况记录
    Performance selectPerformanceByPid(String pid);
}