package com.zw.domain;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeetable.eid
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    private String eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeetable.ename
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeetable.position
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeetable.performanceLevel
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    private Integer performanceLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeetable.contact
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeetable.identityCard
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    private String identityCard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeetable.eid
     *
     * @return the value of employeetable.eid
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeetable.eid
     *
     * @param eid the value for employeetable.eid
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeetable.ename
     *
     * @return the value of employeetable.ename
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeetable.ename
     *
     * @param ename the value for employeetable.ename
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeetable.position
     *
     * @return the value of employeetable.position
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeetable.position
     *
     * @param position the value for employeetable.position
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeetable.performanceLevel
     *
     * @return the value of employeetable.performanceLevel
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public Integer getPerformanceLevel() {
        return performanceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeetable.performanceLevel
     *
     * @param performanceLevel the value for employeetable.performanceLevel
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public void setPerformanceLevel(Integer performanceLevel) {
        this.performanceLevel = performanceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeetable.contact
     *
     * @return the value of employeetable.contact
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeetable.contact
     *
     * @param contact the value for employeetable.contact
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeetable.identityCard
     *
     * @return the value of employeetable.identityCard
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeetable.identityCard
     *
     * @param identityCard the value for employeetable.identityCard
     *
     * @mbggenerated Sat Nov 05 12:43:24 CST 2022
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }
}