package com.zw.domain;

import java.util.Date;

public class Payslip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paysliptable.id
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paysliptable.eid
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    private String eid;

    public String getEname() {
        return ename;
    }

    public void setEname(String ename) {
        this.ename = ename;
    }

    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paysliptable.basicsalary
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    private Integer basicsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paysliptable.allowance
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    private Integer allowance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paysliptable.performance
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    private Integer performance;




    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paysliptable.jobsalary
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    private Integer jobsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paysliptable.overtimesalary
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    private Integer overtimesalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paysliptable.createtime
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    private Date createtime;

    public Integer getSalary() {
        return salary;
    }

    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    private Integer salary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paysliptable.id
     *
     * @return the value of paysliptable.id
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paysliptable.id
     *
     * @param id the value for paysliptable.id
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paysliptable.eid
     *
     * @return the value of paysliptable.eid
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paysliptable.eid
     *
     * @param eid the value for paysliptable.eid
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paysliptable.basicsalary
     *
     * @return the value of paysliptable.basicsalary
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public Integer getBasicsalary() {
        return basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paysliptable.basicsalary
     *
     * @param basicsalary the value for paysliptable.basicsalary
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public void setBasicsalary(Integer basicsalary) {
        this.basicsalary = basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paysliptable.allowance
     *
     * @return the value of paysliptable.allowance
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public Integer getAllowance() {
        return allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paysliptable.allowance
     *
     * @param allowance the value for paysliptable.allowance
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public void setAllowance(Integer allowance) {
        this.allowance = allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paysliptable.performance
     *
     * @return the value of paysliptable.performance
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public Integer getPerformance() {
        return performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paysliptable.performance
     *
     * @param performance the value for paysliptable.performance
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public void setPerformance(Integer performance) {
        this.performance = performance;
    }





    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paysliptable.jobsalary
     *
     * @return the value of paysliptable.jobsalary
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public Integer getJobsalary() {
        return jobsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paysliptable.jobsalary
     *
     * @param jobsalary the value for paysliptable.jobsalary
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public void setJobsalary(Integer jobsalary) {
        this.jobsalary = jobsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paysliptable.overtimesalary
     *
     * @return the value of paysliptable.overtimesalary
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public Integer getOvertimesalary() {
        return overtimesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paysliptable.overtimesalary
     *
     * @param overtimesalary the value for paysliptable.overtimesalary
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public void setOvertimesalary(Integer overtimesalary) {
        this.overtimesalary = overtimesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paysliptable.createtime
     *
     * @return the value of paysliptable.createtime
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paysliptable.createtime
     *
     * @param createtime the value for paysliptable.createtime
     *
     * @mbggenerated Wed Nov 09 23:51:28 CST 2022
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}