package com.zw.domain;

import java.util.Date;

public class Performance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performancetable.pid
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performancetable.eid
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    private String eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performancetable.leavecount
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    private Integer leavecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performancetable.absenteeism
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    private Integer absenteeism;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performancetable.latecount
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performancetable.performanceScore
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    private Integer performanceScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performancetable.piecework
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    private Integer piecework;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performancetable.attendance
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    private Integer attendance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performancetable.recordTime
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    private Date recordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performancetable.fullAttendance
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    private Integer fullAttendance;

    public Integer getOvertimeday() {
        return overtimeday;
    }

    public void setOvertimeday(Integer overtimeday) {
        this.overtimeday = overtimeday;
    }

    private Integer overtimeday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performancetable.pid
     *
     * @return the value of performancetable.pid
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performancetable.pid
     *
     * @param pid the value for performancetable.pid
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performancetable.eid
     *
     * @return the value of performancetable.eid
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performancetable.eid
     *
     * @param eid the value for performancetable.eid
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performancetable.leavecount
     *
     * @return the value of performancetable.leavecount
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public Integer getLeavecount() {
        return leavecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performancetable.leavecount
     *
     * @param leavecount the value for performancetable.leavecount
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public void setLeavecount(Integer leavecount) {
        this.leavecount = leavecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performancetable.absenteeism
     *
     * @return the value of performancetable.absenteeism
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public Integer getAbsenteeism() {
        return absenteeism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performancetable.absenteeism
     *
     * @param absenteeism the value for performancetable.absenteeism
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public void setAbsenteeism(Integer absenteeism) {
        this.absenteeism = absenteeism;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performancetable.performanceScore
     *
     * @return the value of performancetable.performanceScore
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public Integer getPerformanceScore() {
        return performanceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performancetable.performanceScore
     *
     * @param performanceScore the value for performancetable.performanceScore
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public void setPerformanceScore(Integer performanceScore) {
        this.performanceScore = performanceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performancetable.piecework
     *
     * @return the value of performancetable.piecework
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public Integer getPiecework() {
        return piecework;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performancetable.piecework
     *
     * @param piecework the value for performancetable.piecework
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public void setPiecework(Integer piecework) {
        this.piecework = piecework;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performancetable.attendance
     *
     * @return the value of performancetable.attendance
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public Integer getAttendance() {
        return attendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performancetable.attendance
     *
     * @param attendance the value for performancetable.attendance
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public void setAttendance(Integer attendance) {
        this.attendance = attendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performancetable.recordTime
     *
     * @return the value of performancetable.recordTime
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performancetable.recordTime
     *
     * @param recordTime the value for performancetable.recordTime
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performancetable.fullAttendance
     *
     * @return the value of performancetable.fullAttendance
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public Integer getFullAttendance() {
        return fullAttendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performancetable.fullAttendance
     *
     * @param fullAttendance the value for performancetable.fullAttendance
     *
     * @mbggenerated Sun Nov 06 22:19:31 CST 2022
     */
    public void setFullAttendance(Integer fullAttendance) {
        this.fullAttendance = fullAttendance;
    }
}