package com.zw.domain;

import java.util.Date;

public class Wagesscale {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wagesscaletable.wid
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wagesscaletable.basicsalary
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    private Integer basicsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wagesscaletable.allowance
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    private Integer allowance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wagesscaletable.fullattendance
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wagesscaletable.fixedsalary
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */

    public Integer getPerformancesalary() {
        return performancesalary;
    }

    public void setPerformancesalary(Integer performancesalary) {
        this.performancesalary = performancesalary;
    }

    private Integer performancesalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wagesscaletable.createtime
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wagesscaletable.wid
     *
     * @return the value of wagesscaletable.wid
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wagesscaletable.wid
     *
     * @param wid the value for wagesscaletable.wid
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    public void setWid(String wid) {
        this.wid = wid == null ? null : wid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wagesscaletable.basicsalary
     *
     * @return the value of wagesscaletable.basicsalary
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    public Integer getBasicsalary() {
        return basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wagesscaletable.basicsalary
     *
     * @param basicsalary the value for wagesscaletable.basicsalary
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    public void setBasicsalary(Integer basicsalary) {
        this.basicsalary = basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wagesscaletable.allowance
     *
     * @return the value of wagesscaletable.allowance
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    public Integer getAllowance() {
        return allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wagesscaletable.allowance
     *
     * @param allowance the value for wagesscaletable.allowance
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    public void setAllowance(Integer allowance) {
        this.allowance = allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wagesscaletable.fullattendance
     *
     * @return the value of wagesscaletable.fullattendance
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wagesscaletable.createtime
     *
     * @return the value of wagesscaletable.createtime
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wagesscaletable.createtime
     *
     * @param createtime the value for wagesscaletable.createtime
     *
     * @mbggenerated Sun Nov 06 20:27:04 CST 2022
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}